---
services:
  chaindrift:
    image: chaindriftorg/chaindrift:stable
    # image: chaindriftorg/chaindrift:develop
    # Use plotting image
    # image: chaindriftorg/chaindrift:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for chainAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: chaindrift
    volumes:
      - "./user_data:/chaindrift/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.chaindrift.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /chaindrift/user_data/logs/chaindrift.log
      --db-url sqlite:////chaindrift/user_data/tradesv3.sqlite
      --config /chaindrift/user_data/config.json
      --strategy SampleStrategy
